/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.nicaiya.diywidget.model.object;

import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Matrix;
import android.graphics.PointF;
import android.util.Log;

import com.nicaiya.diywidget.BuildConfig;
import com.nicaiya.diywidget.R;
import com.nicaiya.diywidget.ResourceUtil;
import com.nicaiya.diywidget.model.ConfigFileData;
import com.nicaiya.diywidget.model.editable.EditableSize;

import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlSerializer;

public class ShapeLineData extends AbsSizeData implements EditableSize {

    private static final boolean DEBUG = BuildConfig.DEBUG;
    public static final String TAG = ShapeLineData.class.getSimpleName();
    private static final String SUPER_TAG = ShapeLineData.class.getSuperclass().getSimpleName();

    public static final float MAX_SIZE = 800.0f;
    private int color = Color.WHITE;

    public ShapeLineData() {
        setName(ResourceUtil.getString(R.string.shape_line));
    }

    public float getMaxSize() {
        return MAX_SIZE;
    }

    public int getColor() {
        return color;
    }

    public void setColor(int color) {
        if (this.color != color) {
            this.color = color;
            paintInvalidate = true;
        }
    }

    protected void initPaint() {
        super.initPaint();
        if (paintInvalidate) {
            paintInvalidate = false;
            paint.reset();
            paint.setAntiAlias(true);
            paint.setColor(color);
            paint.setAlpha(getAlpha());
            paint.setShadowLayer(getShadowRadius(), getShadowDx(), getShadowDy(), getShadowColor());
        }
    }

    protected void initMatrix() {
        super.initMatrix();
        if (matrixInvalidate) {
            matrixInvalidate = false;
            matrix.reset();
            PointF anchorOffset = getAnchorOffset();
            matrix.preTranslate(getLeft(), getTop());
            matrix.preRotate(getRotate());
            matrix.preTranslate(-anchorOffset.x, -anchorOffset.y);
        }
    }

    protected void initBounds() {
        super.initBounds();
        if (boundsInvalidate) {
            boundsInvalidate = false;
            bounds.set(0x0, -2, (int) getSize(), 2);
        }
    }

    public void draw(Canvas canvas) {
        super.draw(canvas);
        canvas.setMatrix(getMatrix());
        canvas.drawLine(0.0f, 0.0f, getSize(), 0.0f, getPaint());
    }

    public boolean hitTest(int x, int y) {
        float[] pts = {(float) x, (float) y};
        Matrix invertMatrix = new Matrix();
        getMatrix().invert(invertMatrix);
        invertMatrix.mapPoints(pts);
        return getBounds().contains((int) pts[0], (int) pts[1]);
    }

    public void deleteResource() {
        super.deleteResource();
    }

    public void putToXmlSerializer(ConfigFileData configFileData) throws Exception {
        XmlSerializer serializer = configFileData.getXmlSerializer();
        serializer.startTag(ConfigFileData.XML_NAMESPACE, TAG);
        serializer.attribute(ConfigFileData.XML_NAMESPACE, XMLConst.ATTRIBUTE_COLOR, String.valueOf(color));
        super.putToXmlSerializer(configFileData);
        serializer.endTag(ConfigFileData.XML_NAMESPACE, TAG);
    }

    public void updateFromXmlPullParser(ConfigFileData data) {
        XmlPullParser parser = data.getXmlParser();
        try {
            int eventType = parser.getEventType();
            while (eventType != XmlPullParser.END_DOCUMENT) {
                String tag = parser.getName();
                switch (eventType) {
                    case XmlPullParser.START_TAG:
                        if (TAG.equals(tag)) {
                            int count = parser.getAttributeCount();
                            for (int i = 0; i < count; i++) {
                                String attrName = parser.getAttributeName(i);
                                String attrValue = parser.getAttributeValue(i);
                                if (XMLConst.ATTRIBUTE_COLOR.equals(attrName)) {
                                    setColor(Integer.valueOf(attrValue));
                                }
                            }
                        } else if (SUPER_TAG.equals(parser.getName())) {
                            super.updateFromXmlPullParser(data);
                        }
                        break;
                    case XmlPullParser.END_TAG:
                        if (TAG.equals(tag)) {
                            return;
                        }
                        break;
                    default:
                        break;
                }
                eventType = parser.next();
            }
        } catch (Exception e) {
            Log.e(TAG, e.getMessage(), e);
        }
    }

    @Override
    public String toString() {
        return "ShapeLineData{" +
                "color=" + color +
                '}';
    }
}
